/**
 * Canonical Output Generator
 * Gera JSON e Markdown canônico
 * Output sempre igual para o mesmo repositório
 */

import { CanonicalContext } from './canonical-schema'

export interface CanonicalOutput {
  json: string
  markdown: string
  prompt: string
}

/**
 * Generates canonical JSON output
 */
export function generateCanonicalJSON(context: CanonicalContext): string {
  return JSON.stringify(context, null, 2)
}

/**
 * Generates canonical Markdown output
 */
export function generateCanonicalMarkdown(context: CanonicalContext): string {
  const lines: string[] = []
  
  // Header
  lines.push('# Codebase Context')
  lines.push('')
  lines.push(`**Project:** ${context.project.name}`)
  lines.push(`**Blueprint:** ${context.project.blueprint}`)
  lines.push(`**Intent:** ${context.project.intent}`)
  const confidencePercent = context.engine.confidence_level === 'high' ? 85 : context.engine.confidence_level === 'medium' ? 70 : 50
  lines.push(`**Confidence:** ${context.source.confidence.toUpperCase()} (${confidencePercent}%)`)
  lines.push('')
  lines.push(`*Generated by ${context.engine.name} v${context.engine.version} via ${context.source.method}*`)
  lines.push('')
  
  // Project Identity
  lines.push('## Project Identity')
  lines.push(`- **Type:** ${context.project.repository_type}`)
  lines.push(`- **Blueprint:** ${context.project.blueprint}`)
  lines.push(`- **Intent:** ${context.project.intent}`)
  lines.push(`- **Complexity:** ${context.project.complexity}`)
  lines.push(`- **Statefulness:** ${context.project.statefulness}`)
  lines.push(`- **SEO Relevant:** ${context.project.seo_relevant ? 'Yes' : 'No'}`)
  lines.push(`- **Auth Required:** ${context.project.auth_required ? 'Yes' : 'No'}`)
  lines.push('')
  
  // Audience
  lines.push('## Target Audience')
  lines.push(`- **Primary:** ${context.audience.primary}`)
  lines.push(`- **Technical Level:** ${context.audience.technical_level}`)
  lines.push('')
  
  // Proposal
  lines.push('## Core Proposal')
  lines.push('')
  lines.push('### What It Is')
  context.proposal.what_it_is.forEach(item => {
    lines.push(`- ${item}`)
  })
  lines.push('')
  lines.push('### What It Does')
  context.proposal.what_it_does.forEach(item => {
    lines.push(`- ${item}`)
  })
  lines.push('')
  lines.push('### What It Does NOT Do')
  context.proposal.what_it_does_not_do.forEach(item => {
    lines.push(`- ${item}`)
  })
  lines.push('')
  lines.push(`**Core Value Proposition:** ${context.proposal.core_value_proposition}`)
  lines.push('')
  
  // Technical Stack
  lines.push('## Technical Stack')
  lines.push(`- **Framework:** ${context.technical_stack.framework.name}${context.technical_stack.framework.version ? ` (${context.technical_stack.framework.version})` : ''}`)
  lines.push(`- **Languages:** ${context.technical_stack.language.join(', ')}`)
  if (context.technical_stack.styling.length > 0) {
    lines.push(`- **Styling:** ${context.technical_stack.styling.join(', ')}`)
  }
  if (context.technical_stack.ui_libraries.length > 0) {
    lines.push(`- **UI Libraries:** ${context.technical_stack.ui_libraries.join(', ')}`)
  }
  if (context.technical_stack.animation.length > 0) {
    lines.push(`- **Animation:** ${context.technical_stack.animation.join(', ')}`)
  }
  if (context.technical_stack.state_management.length > 0) {
    lines.push(`- **State Management:** ${context.technical_stack.state_management.join(', ')}`)
  }
  if (context.technical_stack.auth) {
    lines.push(`- **Auth:** ${context.technical_stack.auth.provider || context.technical_stack.auth.library}`)
  }
  if (context.technical_stack.database) {
    lines.push(`- **Database:** ${context.technical_stack.database.name || 'Unknown'}${context.technical_stack.database.orm ? ` (ORM: ${context.technical_stack.database.orm})` : ''}`)
  }
  if (context.technical_stack.cms) {
    lines.push(`- **CMS:** ${context.technical_stack.cms.name || 'Unknown'}`)
  }
  if (context.technical_stack.deployment) {
    lines.push(`- **Deployment:** ${context.technical_stack.deployment}`)
  }
  lines.push('')
  
  // Structure
  lines.push('## Structure')
  lines.push(`- **Routing Model:** ${context.structure.routing_model}`)
  lines.push(`- **Entry Point:** ${context.structure.entry_point}`)
  if (context.structure.folder_structure.length > 0) {
    lines.push('### Folder Structure')
    context.structure.folder_structure.forEach(folder => {
      lines.push(`- ${folder}`)
    })
    lines.push('')
  }
  
  // Capabilities
  if (context.capabilities.length > 0) {
    lines.push('## Capabilities')
    context.capabilities.forEach(cap => {
      lines.push(`- ${cap}`)
    })
    lines.push('')
  }
  
  // Limitations
  if (context.limitations.length > 0) {
    lines.push('## Limitations')
    context.limitations.forEach(lim => {
      lines.push(`- ${lim}`)
    })
    lines.push('')
  }
  
  // Excluded Concepts
  if (context.excluded_concepts.length > 0) {
    lines.push('## Excluded Concepts')
    lines.push('The following concepts are explicitly excluded and should not be assumed:')
    context.excluded_concepts.forEach(concept => {
      lines.push(`- ${concept}`)
    })
    lines.push('')
  }
  
  // Risk Flags
  if (context.risk_flags.length > 0) {
    lines.push('## Risk Flags')
    context.risk_flags.forEach(risk => {
      lines.push(`- ${risk}`)
    })
    lines.push('')
  }
  
  // Source
  lines.push('## Source')
  lines.push('- **Method:** ' + context.source.method)
  lines.push('- **Confidence:** ' + context.source.confidence)
  lines.push('')
  
  return lines.join('\n')
}

/**
 * Generates canonical prompt for AI usage
 */
export function generateCanonicalPrompt(context: CanonicalContext): string {
  const confidence = context.source.confidence === 'high' ? 85 : context.source.confidence === 'medium' ? 70 : 50
  const contextJson = JSON.stringify(context, null, 2)
  
  const lines: string[] = []
  lines.push('You are an execution engine.')
  lines.push('')
  lines.push('Use ONLY the context below.')
  lines.push('Do NOT infer features.')
  lines.push('Do NOT introduce systems not listed.')
  lines.push('Do NOT assume user intent.')
  lines.push('If information is missing, respond: "Not detected".')
  lines.push('')
  lines.push('If confidence < 70%, avoid prescriptive decisions.')
  lines.push('')
  lines.push('Context:')
  lines.push(contextJson)
  lines.push('')
  lines.push('Checklist before answering:')
  lines.push('- Did you add something not listed?')
  lines.push('- Did you assume backend or auth?')
  lines.push('- Did you exceed the blueprint?')
  lines.push('')
  lines.push('If yes: remove it or mark as OUT OF SCOPE.')
  lines.push('')
  lines.push(`Current confidence: ${confidence}%`)
  
  return lines.join('\n')
}

/**
 * Generates all canonical outputs
 */
export function generateCanonicalOutputs(context: CanonicalContext): CanonicalOutput {
  return {
    json: generateCanonicalJSON(context),
    markdown: generateCanonicalMarkdown(context),
    prompt: generateCanonicalPrompt(context)
  }
}

